---
- name: Configure NTP servers on VMware host
  community.vmware.vmware_host_ntp:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    esxi_hostname: "{{ inventory_hostname }}"
    ntp_servers: "{{ ntp_servers }}"
    validate_certs: false
    state: present
  check_mode: "{{ check_mode }}"
  register: ntp_result
  delegate_to: localhost

- name: Report NTP assurance result
  include_tasks: report_assurance_result.yml
  vars:
    check_name: "NTP"
    task_result: "{{ ntp_result }}"
    expected_config: "{{ ntp_servers | join(', ') }}"