---
- name: Collect all host configuration facts
  community.vmware.vmware_host_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    esxi_hostname: "{{ inventory_hostname }}"
    validate_certs: false
    schema: vsphere
    properties:
      - config.dateTimeInfo
      - config.network.dnsConfig
      - config.service
      - config.option
      - summary.hardware
      - summary.config
      - config.lockdownMode
      - config.authenticationManagerInfo
      - summary.quickStats
      - hardware.biosInfo
  register: host_facts_async
  delegate_to: localhost
  async: 300
  poll: 0

- name: Wait for host facts collection
  async_status:
    jid: "{{ host_facts_async.ansible_job_id }}"
  register: host_facts
  until: host_facts.finished
  retries: 30
  delay: 2
  delegate_to: localhost

- name: Store host facts for later use
  set_fact:
    collected_host_facts: "{{ host_facts.ansible_facts }}"